name: task_manager
description: A Flutter app to manage tasks with priority and CRUD functionality.

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" # Specify your Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  # Add other dependencies you might need here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # Add any assets you might need here
